Update actions

diff --git a/.github/workflows/pr_check_format_dict.yml b/.github/workflows/pr_check_format_dict.yml
--- a/.github/workflows/pr_check_format_dict.yml
+++ b/.github/workflows/pr_check_format_dict.yml
@@ -1,4 +1,4 @@
-name: Check Dictionary File for PR
+name: Check and Reformat Dictionary File for PR
 
 on:
   workflow_dispatch:
@@ -19,37 +19,36 @@ jobs:
         with:
           ref: ${{ github.head.ref }}
 
-      - uses: actions/checkout@v5
-      - name: Download release artifact
-        uses: actions/download-artifact@v5
+      - name: Download fmld binary from release
+        id: download-release # Give this step an ID to check its result
+        uses: robinraju/release-downloader@v1
         with:
-          name: fmld-linux-binary
-          path: ./fmld
-
+          tag: 'v.0.0.2'
+          fileName: 'fmld'
+          out-file-path: ''
+          
       - name: Make binary executable
-        run: chmod +x ./fmld
+        run: chmod +x fmld
 
-      - name: Run checks
-        id: run_checks
-        continue-on-error: true
-        run: |
-          ./fmld dict/fmld.en.txt > fmld.en.txt.new
-          echo "exit_code=$?" >> $GITHUB_OUTPUT
-
+      - name: Run fmld tool
+        id: run_fmld
+        run: ./fmld dict/fmld.en.txt --txt dict/fmld.en.new.txt
+        
       - name: Handle check failure
-        if: steps.run_checks.outputs.exit_code != '0'
+        if: failure() && steps.run_fmld.outcome == 'failure'
         run: |
-          echo "Tool execution failed. Posting a comment to the PR."
+          echo "FMLD tool execution failed. Posting a comment to the PR."
           gh pr comment ${{ github.event.pull_request.number }} --body "❌ The dictionary file check failed. Please review the errors."
+          exit 1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Handle check success
-        if: steps.run_checks.outputs.exit_code == '0'
+        if: success()
         run: |
           mv fmld.en.txt.new dict/fmld.en.txt
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
           git add dict/fmld.en.txt
-          git commit -m "Automated formatting of fmld.en.txt"
+          git commit -m "Automated reformatting of fmld.en.txt" || exit 0
           git push
